[workspace]

members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.72"
license = "MIT OR Apache-2.0"
keywords = ["minecraft", "server", "api", "plugins"]
categories = ["game-development"]
homepage = "https://github.com/rjacraft"
repository = "https://github.com/rjacraft/rjacraft"
include = ["/src", "/examples"]

[workspace.dependencies]
# Bevy game engine
bevy_ecs = "0.11.2"
bevy_app = "0.11.2"
tokio = "1.32.0"
byteorder = "1.4.3"
serde_json = "1.0.105"

# Documentation
document-features = "0.2.7"

# Own crates
rjacraft_core = { path = "crates/core", version = "0.0.1" }
rjacraft_network = { path = "crates/network", version = "0.0.1" }
rjacraft_protocol = { path = "crates/protocol", version = "0.0.1" }

# Bevy-specific profile setup aimed at better performace while developing

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[package]
name = "rjacraft"
description = "Minecraft server development suite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Rjacraft components
rjacraft_core = { workspace = true, optional = true }
rjacraft_network = { workspace = true }
rjacraft_protocol = { workspace = true }
bevy_app.workspace = true
bevy_ecs.workspace = true
serde_json.workspace = true

# Documentation
document-features.workspace = true

[features]

#! ## Basic features

## Enables the default features
default = ["core"]

## Enables `core` features
core = ["dep:rjacraft_core"]
